config/routes.rb
Rails.application.routes.draw do
  
  # get 'profiles/show'

  # get 'profiles/edit'
  get 'profiles_show/:id' => 'profiles#show', as: 'profiles_show'
  get 'profiles_edit/:id' => 'profiles#edit', as: 'profiles_edit'
  
  ActiveAdmin.routes(self)
  resources :profiles
  resources :galleries do
  	resources :notices
  end
  devise_for :users
  root "galleries#index"
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	belongs_to :user
	has_many :notices
	has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>'},
                    default_url: '/images/:style/missing.png'
    validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']
    

end

app/models/notice.rb
class Notice < ApplicationRecord
	belongs_to :user
	belongs_to :gallery
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    has_many :notices
    has_many :galleries
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true, length: {maximum: 50}
	validates :email, uniqueness: true, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end
  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: :create
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.order(created_at: :desc).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:title, :user_id, :image)
    end
end

app/controllers/notices_controller.rb
class NoticesController < InheritedResources::Base
  before_action :set_gallery
  before_action :authenticate_user!, only: :create
  def new
    @notice = Notice.new
  end
  def index
    @notices = Notice.order(created_at: :desc)
  end
  def create
    @notice = @gallery.notices.build(notice_params)
    @notice.user_id = current_user.id

    if @notice.save
      flash[:success] = "You noticeed the hell out of that gallery!"
      redirect_to :back
    else
      flash[:alert] = "Check the notice form, something went horribly wrong."
      render root_path
    end
  end
  def destroy
    
    @notice = @gallery.notices.find(params[:id])

    @notice.destroy
    flash[:success] = "notice deleted"
    redirect_to :back
 
  end
  private

    def notice_params
      params.require(:notice).permit(:user_id, :notice_id, :body, :mark)
    end
    def set_gallery
      @gallery = Gallery.find(params[:gallery_id])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@galleries = User.find(params[:id]).galleries
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/_form.html.erb
<%= form_for(gallery) do |f| %>
  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
</br><h1>Galleries</h1>

<div class="row">

  <div class="">
    <div class="row">
      <div class="col-sm-12 products-pagination">
            <%= will_paginate @galleries %>
      </div>
    </div>



    <div class="row">
      <% @galleries.each do |gallery| %>

          <div class="col-sm-4 product-item">
            <div class="panel panel-default">
              <div class="panel-body" align="center">
                <div class="img"> <%= link_to image_tag(gallery.image.url(:medium), size: '150'), gallery_path(gallery)  %></div>
                <h3><%= gallery.title %></h3>
                <h4> By <%= gallery.user.name %></h4>
              </div>
            </div>
          </div>

      <% end %>
    </div>


  </div>

</div>


<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>
</br>
</br>
<p>

  <h3><%= @gallery.title %></h3>
</p>
<div class="img"> <%= image_tag(@gallery.image.url(:medium), size: '300')  %></div>
<p>
  <strong>User:</strong>
  <%= @gallery.user.name %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>
<% if @gallery.notices %>
        <% sum = 0 %>
        <% @gallery.notices.each do |notice| %>
          <div class="notice">
            Author: <div class="user-name">
              <%= notice.user.name %>
            </div></br>
            Comment: <div class="notice-content">
              <%= notice.body %>
            </div>
            Mark: <div class="notice-content">
              <%= notice.mark %>
              <% sum = sum + notice.mark.to_i %>
            </div>
           
            <% if notice.user == current_user %>
              <%= link_to gallery_notice_path(@gallery, notice), method: :delete do %>
                <span class="glyphicon glyphicon-remove delete-notice"> </span>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
Average mark: <%= sum / @gallery.notices.count.to_f %> </br> 
<h3>Create a notice</h3>
    <div class="notice-form row">
      <div class="notice-form col-sm-11">
        <%= form_for [@gallery, @gallery.notices.new] do |f| %>
          <%= f.text_field :body, placeholder: 'Add a notice...' %>
          <%= f.hidden_field :gallery_id, value: @gallery.id %>
          <%= f.select(:mark, options_for_select(1..5)) %>
        <% end %>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoGallery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/application/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Main', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <p class="navbar-text">
              Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %> <span class="glyphicon glyphicon-heart delete-like"> </span>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete,  class: 'navbar-link'  %><span class="glyphicon glyphicon-heart delete-like"> </span>
              <%= link_to 'Profile', profile_path(current_user.id),  class: 'navbar-link'  %>
            </p>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/notices/_form.html.erb
<%= form_for @gallery.comments.build, remote: true do |f| %>
  <div>
    <%= f.hidden_field :gallery_id, value: @gallery.id %>  
  </div>
  <div>
    <%= f.hidden_field :user_id, value: @user.id %>    
  </div>
  <div>
    Mark: <%= f.select(:mark, options_for_select(1..5)) %>
  </div>
  <div>
    Text: <%= f.text_area :body %>
  </div>

  <%= f.submit %>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notices</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Gallery</th>
      <th>Body</th>
      <th>Mark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.user_id %></td>
        <td><%= notice.gallery_id %></td>
        <td><%= notice.body %></td>
        <td><%= notice.mark %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notice.user_id %>
</p>

<p>
  <strong>Gallery:</strong>
  <%= @notice.gallery_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @notice.body %>
</p>

<p>
  <strong>Mark:</strong>
  <%= @notice.mark %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>

app/views/profiles/show.html.erb
</br>
<em><center><h1>Profile of <%= @user.name.upcase %></h1></center></em>
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', profiles_edit_path(@user[:id]),  class: 'btn edit-button' %> | 
                <h1>Create new photo</h1> 
		        <%= form_for (Gallery.new) do |f| %>
		        <%= f.hidden_field :user_id, value: current_user.id %>
		        <%= f.file_field :image %>
		        <%= f.text_field :title %>
		        <%= f.submit %>
		        <% end %> 
    
          <% end %>            
      
        </span>
      </div>
      
    </div>
  </div>
</div>

<% @user.galleries.each do |gallery| %>
  <%= gallery.title %>
  <div class="img"> <%= link_to image_tag(gallery.image.url(:medium), size: '150'), gallery_path(gallery)  %></div>

<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>